#!/bin/sh

start() {
  if ! pgrep -f $1 ;
  then
    $@&
  fi 
}

# Compositor
start picom --experimental-backends --config $HOME/.config/awesome/theme/picom.conf

# Screen resolution
start $HOME/.screenlayout/layoutAcerLaptop.sh

# Load X colors
start xrdb $HOME/.Xresources

# System Services
start /usr/lib/policykit-1-pantheon/io.elementary.desktop.agent-polkit
start /usr/lib/geoclue2-1-pantheon/pantheon-agent-geoclue2
start io.elementary.notifications
start io.elementary.calendar --background
# VBox only
#start /usr/bin/VBoxClient-all

# Topbar
start io.elementary.wingpanel
