#!/bin/sh

start() {
  if ! pgrep -f $1 ;
  then
    $@&
  fi 
}

killAndStart() {
	# Terminate already running bar instances
	killall -q $1
	# Wait until the processes have been shut down
	while pgrep -u $UID -x $1 >/dev/null; do sleep 1; done
	# Relaunch
	sleep 2
	$@&
}

# Compositor
start picom --experimental-backends --config $HOME/.config/awesome/theme/picom.conf

# Screen resolution
start $HOME/.screenlayout/layoutAcer.sh

# Load X colors
start xrdb $HOME/.Xresources

# Topbar
killAndStart io.elementary.wingpanel

# System Services
start /usr/lib/policykit-1-pantheon/io.elementary.desktop.agent-polkit
start /usr/lib/geoclue2-1-pantheon/pantheon-agent-geoclue2
start io.elementary.notifications
start io.elementary.calendar --background
# VBox only
#start /usr/bin/VBoxClient-all

